services:
  provision-minecraft:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: FABRIC
      SETUP_ONLY: "TRUE"
      VERSION: "1.20.1"
      VANILLATWEAKS_FILE: |
        /vanillatweaks/resourcepacks.json
      MODRINTH_PROJECTS: |
        fabric-api
        chat-signing-hider
        lambdynamiclights
        raised
        simple-voice-chat
        tooltipfix
        shulkerboxtooltip
        bookshelf-lib
        directionhud
        lithium
        sodium
        iris
        modmenu
        distanthorizons
      MODRINTH_ALLOWED_VERSION_TYPE: alpha
    volumes:
      - /opt/data:/data
      - /tmp/percycraft/percycraft-smp-ami/vanillatweaks:/vanillatweaks:ro
    restart: no
