[sources.percycraft]
type = "journald"
include_units = ["percycraft", "status"]

[sinks.cloudwatch]
type = "aws_cloudwatch_logs"
inputs = ["percycraft"]
group_name = "percycraft"
stream_name = "percycraft"
encoding.codec = "json"
