version: "3.8"
services:
  mc_init:
    image: itzg/minecraft-server
    environment:
      TYPE: FABRIC
      VERSION: "1.20.1"
      VANILLATWEAKS_FILE: |
        /vanillatweaks/resourcepacks.json
      REMOVE_OLD_VANILLATWEAKS: "TRUE"
      MODRINTH_PROJECTS: |
        fabric-api
        simple-voice-chat
    volumes:
      - ./fs:/init
      - ./:/output
      - mc-init-data:/data
      - fs-data:/web
      - ./mc/vanillatweaks:/vanillatweaks:ro
    restart: "no"
    entrypoint: ["/init/start.sh"]
  fs:
    image: halverneus/static-file-server
    volumes:
      - fs-data:/web:ro
    ports:
      - "8080:8080"
    restart: unless-stopped
volumes:
  mc-init-data:
  fs-data:
