version: "3.8"
services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: FABRIC
      VERSION: "1.20.1"
      MOTD: §k* §l§6Welcome §fto the §l§cPercycraft §fserver! §k*
      VANILLATWEAKS_FILE: |
        /vanillatweaks/datapacks.json,
        /vanillatweaks/craftingtweaks.json
      REMOVE_OLD_VANILLATWEAKS: "TRUE"
      RESOURCE_PACK: ${RESOURCE_PACK}
      RESOURCE_PACK_SHA1: ${RESOURCE_PACK_SHA1}
      RESOURCE_PACK_ENFORCE: "TRUE"
      EXISTING_WHITELIST_FILE: SYNCHRONIZE
      WHITELIST_FILE: /config/allowlist.json
      EXISTING_OPS_FILE: SYNCHRONIZE
      OPS_FILE: /config/ops.json
      MEMORY: 4G
      MODRINTH_PROJECTS: |
        fabric-api
        audioplayer
        chat-signing-hider
        coord-finder
        lambdynamiclights
        raised
        simple-voice-chat
        tooltipfix
      RCON_CMDS_STARTUP: |-
        /gamerule playersSleepingPercentage 0
      TZ: "Europe/London"
    volumes:
      - mc-data:/data
      - ./mc/vanillatweaks:/vanillatweaks:ro
      - ./mc/config:/config:ro
    ports:
      - "25565:25565"
      - "24454:24454/udp"
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  mc-data:
