version: "3.8"
services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: FABRIC
      VERSION: ${MINECRAFT_VERSION:-LATEST}
      MOTD: §k* §l§6Welcome §fto the §l§cPercycraft §fserver! §k*
      VANILLATWEAKS_FILE: |
        /vanillatweaks/datapacks.json,
        /vanillatweaks/resourcepacks.json,
        /vanillatweaks/craftingtweaks.json
      REMOVE_OLD_VANILLATWEAKS: "TRUE"
      EXISTING_WHITELIST_FILE: SYNCHRONIZE
      WHITELIST_FILE: /config/allowlist.json
      EXISTING_OPS_FILE: SYNCHRONIZE
      OPS_FILE: /config/ops.json
      MEMORY: 4G
      RESOURCE_PACK: http://localhost:8080/resourcepacks/VanillaTweaks_c32f2d5.zip
      RESOURCE_PACK_SHA1: fa056588583b15943e5774231b1dbefaee3f519a
      RESOURCE_PACK_ENFORCE: "TRUE"
      MODRINTH_PROJECTS: |
        fabric-api
        audioplayer
        chat-signing-hider
        coord-finder
        lambdynamiclights
        raised
        simple-voice-chat
        tooltipfix
    volumes:
      - mc-data:/data
      - ./mc/vanillatweaks:/vanillatweaks:ro
      - ./mc/config:/config:ro
      - ./mc/scripts:/scripts
    ports:
      - "25565:25565"
      - "24454:24454/udp"
    stdin_open: true
    tty: true
    restart: unless-stopped
    command: /scripts/post_startup.sh
  fs:
    image: halverneus/static-file-server
    volumes:
      - mc-data:/web:ro
    ports:
      - "8080:8080"
volumes:
  mc-data:
