version: "3.8"
services:
  mc:
    depends_on:
      restore:
        condition: service_completed_successfully
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: FABRIC
      VERSION: "1.20.1"
      MOTD: §k* §l§6Welcome §fto the §l§cPercycraft §fserver! §k*
      VANILLATWEAKS_FILE: |
        /vanillatweaks/datapacks.json,
        /vanillatweaks/craftingtweaks.json
      RESOURCE_PACK: ${RESOURCE_PACK}
      RESOURCE_PACK_SHA1: ${RESOURCE_PACK_SHA1}
      RESOURCE_PACK_ENFORCE: "TRUE"
      EXISTING_WHITELIST_FILE: SYNCHRONIZE
      WHITELIST_FILE: /config/allowlist.json
      EXISTING_OPS_FILE: SYNCHRONIZE
      OPS_FILE: /config/ops.json
      MEMORY: 3G
      MODRINTH_PROJECTS: |
        fabric-api
        audioplayer
        chat-signing-hider
        coord-finder
        lambdynamiclights
        raised
        simple-voice-chat
        tooltipfix
        fabricquilt-chunk-pregenerator
      RCON_PASSWORD: ${PASSWORD}
      RCON_CMDS_STARTUP: |-
        /gamerule playersSleepingPercentage 0
        /pregen start 25
      RCON_CMDS_FIRST_CONNECT: |-
        /pregen stop
      RCON_CMDS_LAST_DISCONNECT: |-
        /function kill_empty_boats:run
        /pregen start 25
      TZ: "Europe/London"
      ICON: /resources/server-icon.png
      OVERRIDE_ICON: "TRUE"
    volumes:
      - /efs/data:/data
      - /percycraft/mc/vanillatweaks:/vanillatweaks:ro
      - /percycraft/mc/config:/config:ro
      - /percycraft/mc/resources/:/resources:ro
    ports:
      - "25575:25575"
      - "25565:25565"
      - "24454:24454/udp"
    stdin_open: true
    tty: true
    restart: unless-stopped
  fs:
    image: halverneus/static-file-server
    volumes:
      - /efs/web:/web:ro
    ports:
      - "8080:8080"
    restart: unless-stopped
  restore:
    image: itzg/mc-backup
    restart: no
    entrypoint: restore-tar-backup
    volumes:
      - /efs/data:/data
      - /efs/backups:/backups:ro
  backup:
    image: itzg/mc-backup
    depends_on:
      mc:
        condition: service_healthy
    restart: unless-stopped
    environment:
      BACKUP_INTERVAL: "24h"
      RCON_HOST: mc
      RCON_PASSWORD: ${PASSWORD}
      PRUNE_BACKUPS_DAYS: 14
      INITIAL_DELAY: 0
      LINK_LATEST: "TRUE"
      TZ: "Europe/London"
    volumes:
      - /efs/data:/data:ro
      - /efs/backups:/backups

