version: "3.8"
services:
  mc_init:
    image: itzg/minecraft-server
    environment:
      TYPE: FABRIC
      VERSION: "1.20.1"
      VANILLATWEAKS_FILE: |
        /vanillatweaks/resourcepacks.json
      MODRINTH_PROJECTS: |
        fabric-api
        simple-voice-chat
    volumes:
      - /percycraft/mc_init/start.sh:/start.sh
      - /percycraft:/output
      - /efs/web:/web
      - /percycraft/mc/vanillatweaks:/vanillatweaks:ro
    restart: "no"
    entrypoint: ["/start.sh"]
