services:
  provision-minecraft:
    image: itzg/minecraft-server:base
    environment:
      EULA: "TRUE"
      TYPE: FABRIC
      SETUP_ONLY: "TRUE"
      VERSION: "1.20.1"
      MODE: creative      
      MODRINTH_PROJECTS: |
        fabric-api
        simple-voice-chat
        pl3xmap:beta
        bookshelf-lib
        better-fabric-console
        lithium
        create-fabric:beta
      ICON: /resources/server-icon.png
      OVERRIDE_ICON: "TRUE"
    volumes:
      - /opt/data:/data
      - /tmp/percycraft/create-anything-ami/resources/:/resources:ro
    restart: no
