version: "3.8"
services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: CUSTOM
      CUSTOM_SERVER: ${CUSTOM_SERVER}
      FAMILY: FABRIC
      MOTD: §k* §l§6Welcome §fto the §l§cPercycraft §fserver! §k*
      RESOURCE_PACK: ${RESOURCE_PACK}
      RESOURCE_PACK_SHA1: ${RESOURCE_PACK_SHA1}
      EXISTING_WHITELIST_FILE: SKIP
      EXISTING_OPS_FILE: SKIP
      MEMORY: 6G
      STOP_SERVER_ANNOUCE_DELAY: 60
      STOP_DURATION: 240
      RCON_PASSWORD: ${PASSWORD}
      RCON_CMDS_STARTUP: |-
        /gamerule playersSleepingPercentage 0
        /pregen start 25
      RCON_CMDS_FIRST_CONNECT: |-
        /pregen stop
      RCON_CMDS_LAST_DISCONNECT: |-
        /function kill_empty_boats:run
        /pregen start 25
      TZ: "Europe/London"
    stop_grace_period: 5m
    volumes:
      - /opt/data:/data
    ports:
      - "25575:25575"
      - "25565:25565"
      - "8100:8100"
      - "24454:24454/udp"
    stdin_open: true
    tty: true
    restart: no
