version: "3.8"
services:
  mc:
    image: itzg/minecraft-server
    networks:
      - mc-network
    environment:
      EULA: "TRUE"
      TYPE: CUSTOM
      CUSTOM_SERVER: ${CUSTOM_SERVER}
      FAMILY: FABRIC
      MOTD: §k* §l§6Welcome §fto the §l§cPercycraft §fserver! §k*
      RESOURCE_PACK: ${RESOURCE_PACK}
      RESOURCE_PACK_SHA1: ${RESOURCE_PACK_SHA1}
      EXISTING_WHITELIST_FILE: SKIP
      EXISTING_OPS_FILE: SKIP
      MEMORY: 3G
      STOP_SERVER_ANNOUCE_DELAY: 60
      STOP_DURATION: 240
      RCON_PASSWORD: ${PASSWORD}
      RCON_CMDS_STARTUP: |-
        /gamerule playersSleepingPercentage 0
        /pregen start 25
        /team add New
        /team add Old
      RCON_CMDS_ON_CONNECT: |-
        /team join New @a[team=]
        ${WELCOME_MESSAGE}
        /team join Old @a[team=New]
      RCON_CMDS_FIRST_CONNECT: |-
        /pregen stop
      RCON_CMDS_LAST_DISCONNECT: |-
        /function kill_empty_boats:run
        /pregen start 25
      TZ: "Europe/London"
    stop_grace_period: 5m
    volumes:
      - /efs/data:/data
    ports:
      - "25575:25575"
      - "25565:25565"
      - "24454:24454/udp"
    stdin_open: true
    tty: true
    restart: no
  fs:
    image: halverneus/static-file-server
    volumes:
      - /efs/web:/web:ro
    ports:
      - "8080:8080"
    restart: no
networks:
  mc-network:
