version: "3.8"
services:
  install-minecraft:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: FABRIC
      SETUP_ONLY: "TRUE"
      VERSION: "1.20.1"
      VANILLATWEAKS_FILE: |
        /vanillatweaks/datapacks.json,
        /vanillatweaks/resourcepacks.json
        /vanillatweaks/craftingtweaks.json
      MODRINTH_PROJECTS: |
        fabric-api
        chat-signing-hider
        lambdynamiclights
        raised
        simple-voice-chat
        tooltipfix
        fabricquilt-chunk-pregenerator
        pl3xmap
        shulkerboxtooltip
        lmd
        friendly-fire
        bookshelf-lib
        directionhud
        better-fabric-console
        enhanced-groups
        lithium
        sodium
        iris
        individual-keep-inventory
      MODRINTH_ALLOWED_VERSION_TYPE: beta
      ICON: /resources/server-icon.png
      OVERRIDE_ICON: "TRUE"      
    volumes:
      - /opt/data:/data
      - /opt/percycraft/install-minecraft/vanillatweaks:/vanillatweaks:ro
      - /opt/percycraft/install-minecraft/resources/:/resources:ro  
    restart: no
