version: "3.8"
services:
  minecraft:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: CUSTOM
      CUSTOM_SERVER: ${CUSTOM_SERVER}
      FAMILY: FABRIC
      MOTD: Welcome to the Percycraft server!
      RESOURCE_PACK: ${RESOURCE_PACK}
      RESOURCE_PACK_SHA1: ${RESOURCE_PACK_SHA1}
      WHITELIST: ${WHITELIST}
      EXISTING_WHITELIST_FILE: SKIP
      MEMORY: 6G
      STOP_SERVER_ANNOUCE_DELAY: 60
      STOP_DURATION: 240
      RCON_PASSWORD: ${PASSWORD}
      RCON_CMDS_STARTUP: |-
        /gamerule playersSleepingPercentage 0
        /pregen start 25
      RCON_CMDS_FIRST_CONNECT: |-
        /pregen stop
      RCON_CMDS_LAST_DISCONNECT: |-
        /function kill_empty_boats:run
        /pregen start 25
      TZ: ${TZ}
    stop_grace_period: 5m
    volumes:
      - /opt/data:/data
    ports:
      - "25575:25575"
      - "25565:25565"
      - "8080:8080"
      - "24454:24454/udp"
    stdin_open: true
    tty: true
    restart: no
