services:
  provision-minecraft:
    image: itzg/minecraft-server:base
    environment:
      EULA: "TRUE"
      TYPE: FABRIC
      SETUP_ONLY: "TRUE"
      VERSION: "1.20.1"
      VANILLATWEAKS_FILE: |
        /vanillatweaks/datapacks.json
        /vanillatweaks/craftingtweaks.json
      MODRINTH_PROJECTS: |
        fabric-api
        simple-voice-chat
        fabricquilt-chunk-pregenerator
        pl3xmap:beta
        lmd
        friendly-fire
        bookshelf-lib
        directionhud
        better-fabric-console
        enhanced-groups:alpha
        lithium
        individual-keep-inventory
      ICON: /resources/server-icon.png
      OVERRIDE_ICON: "TRUE"
    volumes:
      - /opt/data:/data
      - /tmp/percycraft/percycraft-smp-ami/vanillatweaks:/vanillatweaks:ro
      - /tmp/percycraft/percycraft-smp-ami/resources/:/resources:ro
    restart: no
