services:
  minecraft:
    image: itzg/minecraft-server:base
    env_file:
      - /opt/.env
    environment:
      EULA: "TRUE"
      TYPE: CUSTOM
      FAMILY: FABRIC
      MOTD: Welcome to the Percycraft server!
      MEMORY: 6G
      STOP_SERVER_ANNOUCE_DELAY: 60
      STOP_DURATION: 240
      RCON_CMDS_STARTUP: |-
        /gamerule playersSleepingPercentage 0
        /pregen start 25
      RCON_CMDS_FIRST_CONNECT: |-
        /pregen stop
      RCON_CMDS_LAST_DISCONNECT: |-
        /function kill_empty_boats:run
        /pregen start 25
    stop_grace_period: 5m
    volumes:
      - /opt/data:/data
    ports:
      - "25575:25575"
      - "25565:25565"
      - "8080:8080"
      - "24454:24454/udp"
    stdin_open: true
    tty: true
    restart: no
