[sources.lobby]
type = "journald"
include_units = ["lobby"]

[sinks.cloudwatch]
type = "aws_cloudwatch_logs"
inputs = ["lobby"]
group_name = "percycraft"
stream_name = "{{ host }}"
encoding.codec = "json"
