[sources.lobby]
type = "journald"
include_units = ["smp", "create"]

[sinks.cloudwatch]
type = "aws_cloudwatch_logs"
inputs = ["smp", "create"]
group_name = "percycraft"
stream_name = "lobby"
encoding.codec = "json"
