name: Deploy Percycraft

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
      id-token: write
      contents: read

jobs:
  PrepareChangeSet:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::719158693954:role/Percycraft
          role-session-name: GithubDeployPercycraft
          aws-region: eu-west-2
      - name: Deploy Survival
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: percycraft
          template: aws/cf.yml
          parameter-overrides: "KeyPairName=${{ secrets.KEYPAIRNAME }},YourIPv4=${{ secrets.YOURIPV4 }},Players=\"${{ secrets.PLAYERS }}\",CurseForgeAPIKey=${{ secrets.CURSEFORGEAPIKEY }},Profile=survival,WeekdayStartSchedule=\"\",WeekdayStopSchedule=\"\",WeekendStartSchedule=\"\",WeekendStopSchedule=\"\""
          no-execute-changeset: 1
          no-fail-on-empty-changeset: 1
      - name: Deploy Creative
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: create-anything
          template: aws/cf.yml
          parameter-overrides: "KeyPairName=${{ secrets.KEYPAIRNAME }},YourIPv4=${{ secrets.YOURIPV4 }},Players=\"${{ secrets.CREATIVEPLAYERS }}\",CurseForgeAPIKey=${{ secrets.CURSEFORGEAPIKEY }},Profile=creative,FileServerHostName=cdn2.pcraft.co.uk,WeekdayStartSchedule=\"\",WeekdayStopSchedule=\"\",WeekendStartSchedule=\"\",WeekendStopSchedule=\"\""
          no-execute-changeset: 1
          no-fail-on-empty-changeset: 1          
