name: Deploy Percycraft

on:
  - push

permissions:
  id-token: write
  contents: read

jobs:
  build-trigger:
    runs-on: ubuntu-latest
    outputs:
      percycraft-base: ${{ steps.percycraft-base.outputs.src }}
      percycraft-smp: ${{ steps.percycraft-smp.outputs.src }}
      aws: ${{ steps.aws.outputs.src }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v3
      id: percycraft-base
      with:
        base: ${{ github.ref }}
        filters: |
          src:
            - 'percycraft-base/**'
    - uses: dorny/paths-filter@v3
      id: percycraft-smp
      with:
        base: ${{ github.ref }}
        filters: |
          src:
            - 'percycraft-smp/**'
    - uses: dorny/paths-filter@v3
      id: aws
      with:
        base: ${{ github.ref }}
        filters: |
          src:
            - 'aws/**'
  percycraft-base:
    needs: build-trigger
    if: needs.build-trigger.outputs.percycraft-base == 'true'
    runs-on: ubuntu-latest
    name: Create percycraft-base AMI
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::719158693954:role/Percycraft
          role-session-name: GithubDeployPercycraft
          aws-region: eu-west-2
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: latest
      - name: Run `packer init`
        id: init
        run: "packer init percycraft-base/"
      - name: Run `packer validate`
        id: validate
        run: "packer validate percycraft-base/"
      - name: Build AMI
        id: build
        run: "packer build percycraft-base/percycraft-base.pkr.hcl"
  percycraft-smp:
    needs:
      - build-trigger
      - percycraft-base
    if: needs.build-trigger.outputs.percycraft-smp == 'true'
    runs-on: ubuntu-latest
    name: Create percycraft-smp AMI
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::719158693954:role/Percycraft
          role-session-name: GithubDeployPercycraft
          aws-region: eu-west-2
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: latest
      - name: Run `packer init`
        id: init
        run: "packer init percycraft-smp/"
      - name: Run `packer validate`
        id: validate
        run: "packer validate percycraft-smp/"
      - name: Build AMI
        id: build
        run: "packer build percycraft-smp/percycraft-smp.pkr.hcl"
  PrepareChangeSet:
    needs:
      - build-trigger
      - percycraft-smp
    if: needs.build-trigger.outputs.aws == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::719158693954:role/Percycraft
          role-session-name: GithubDeployPercycraft
          aws-region: eu-west-2
      - name: Deploy Survival
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: percycraft
          template: aws/cf.yml
          parameter-overrides: "KeyPairName=${{ secrets.KEYPAIRNAME }},YourIPv4=${{ secrets.YOURIPV4 }},Players=\"${{ secrets.PLAYERS }}\",CurseForgeAPIKey=${{ secrets.CURSEFORGEAPIKEY }},Profile=survival,WeekdayStartSchedule=\"\",WeekdayStopSchedule=\"\",WeekendStartSchedule=\"\",WeekendStopSchedule=\"\""
          no-execute-changeset: 1
          no-fail-on-empty-changeset: 1
      - name: Deploy Creative
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: create-anything
          template: aws/cf.yml
          parameter-overrides: "KeyPairName=${{ secrets.KEYPAIRNAME }},YourIPv4=${{ secrets.YOURIPV4 }},Players=\"${{ secrets.CREATIVEPLAYERS }}\",CurseForgeAPIKey=${{ secrets.CURSEFORGEAPIKEY }},Profile=creative,FileServerHostName=cdn2.pcraft.co.uk,WeekdayStartSchedule=\"\",WeekdayStopSchedule=\"\",WeekendStartSchedule=\"\",WeekendStopSchedule=\"\""
          no-execute-changeset: 1
          no-fail-on-empty-changeset: 1
